wtxlog/account/forms.py
# -*- coding: utf-8 -*-

from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from ..models import User


class LoginForm(Form):
    email = StringField('Email', validators=[DataRequired(), Length(1, 64),
                                             Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Keep me logged in')
    submit = SubmitField('Log In')


class RegistrationForm(Form):
    email = StringField('Email',
                        validators=[DataRequired(), Length(1, 64), Email()])

    username = StringField('Username', validators=[
        DataRequired(), Length(1, 64), Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                              'Usernames must have only letters, '
                                              'numbers, dots or underscores')])
    password = PasswordField('Password', validators=[
        DataRequired(), EqualTo('password2', message='Passwords must match.')])
    password2 = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField('Register')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')


class ChangePasswordForm(Form):
    old_password = PasswordField('Old password', validators=[DataRequired()])
    password = PasswordField('New password', validators=[
        DataRequired(), EqualTo('password2', message='Passwords must match')])
    password2 = PasswordField('Confirm new password', validators=[DataRequired()])
    submit = SubmitField('Update Password')


class PasswordResetRequestForm(Form):
    email = StringField('Email', validators=[DataRequired(), Length(1, 64),
                                             Email()])
    submit = SubmitField('Reset Password')


class PasswordResetForm(Form):
    email = StringField('Email', validators=[DataRequired(), Length(1, 64),
                                             Email()])
    password = PasswordField('New Password', validators=[
        DataRequired(), EqualTo('password2', message='Passwords must match')])
    password2 = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField('Reset Password')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first() is None:
            raise ValidationError('Unknown email address.')


class ChangeEmailForm(Form):
    email = StringField('New Email', validators=[DataRequired(), Length(1, 64),
                                                 Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Update Email Address')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

wtxlog/account/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

account = Blueprint('account', __name__, template_folder='templates',
                    static_folder='static')

from . import views

wtxlog/account/views.py
# -*- coding: utf-8 -*-

from . import account

from flask import flash, url_for, redirect, request, render_template
from flask.ext.login import login_user, logout_user, login_required, current_user

from ..utils.email import send_email
from ..models import db, User
from .forms import *


@account.route("/")
@login_required
def index():
    return render_template('index.html')


@account.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        errmsg, user = User.authenticate(form.email.data, form.password.data)
        if errmsg is None and isinstance(user, User):
            login_user(user, form.remember_me.data)
            return redirect(request.args.get('next') or url_for('.index'))
        flash(errmsg)
    return render_template('login.html', form=form)


@account.route('/logout/')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('.index'))


@account.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        token = user.generate_confirmation_token()
        send_email(user.email, 'Confirm Your Account',
                   'email/confirm', user=user, token=token)
        flash('A confirmation email has been sent to you by email.')
        return redirect(url_for('.login'))
    return render_template('register.html', form=form)


@account.route('/confirm/<token>/')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('.index'))
    if current_user.confirm(token):
        flash('You have confirmed your account. Thanks!')
    else:
        flash('The confirmation link is invalid or has expired.')
    return redirect(url_for('.index'))


@account.route('/confirm/')
@login_required
def resend_confirmation():
    token = current_user.generate_confirmation_token()
    send_email(current_user.email, 'Confirm Your Account',
               'email/confirm', user=current_user, token=token)
    flash('A new confirmation email has been sent to you by email.')
    return redirect(url_for('.index'))


@account.route('/change-password/', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.password = form.password.data
            db.session.add(current_user)
            db.session.commit()
            flash('Your password has been updated.')
            return redirect(url_for('.index'))
        else:
            flash('Invalid password.')
    return render_template("change_password.html", form=form)


@account.route('/reset/', methods=['GET', 'POST'])
def password_reset_request():
    if not current_user.is_anonymous():
        return redirect(url_for('.index'))
    form = PasswordResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            token = user.generate_reset_token()
            send_email(user.email, 'Reset Your Password',
                       'email/reset_password',
                       user=user, token=token,
                       next=request.args.get('next'))
        flash('An email with instructions to reset your password has been '
              'sent to you.')
        return redirect(url_for('.login'))
    return render_template('reset_password.html', form=form)


@account.route('/reset/<token>/', methods=['GET', 'POST'])
def password_reset(token):
    if not current_user.is_anonymous():
        return redirect(url_for('.index'))
    form = PasswordResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            return redirect(url_for('.index'))
        if user.reset_password(token, form.password.data):
            flash('Your password has been updated.')
            return redirect(url_for('.login'))
        else:
            return redirect(url_for('.index'))
    return render_template('reset_password.html', form=form)


@account.route('/change-email/', methods=['GET', 'POST'])
@login_required
def change_email_request():
    form = ChangeEmailForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.password.data):
            new_email = form.email.data
            token = current_user.generate_email_change_token(new_email)
            send_email(new_email, 'Confirm your email address',
                       'email/change_email',
                       user=current_user, token=token)
            flash('An email with instructions to confirm your new email '
                  'address has been sent to you.')
            return redirect(url_for('.index'))
        else:
            flash('Invalid email or password.')
    return render_template("change_email.html", form=form)


@account.route('/change-email/<token>/')
@login_required
def change_email(token):
    if current_user.change_email(token):
        flash('Your email address has been updated.')
    else:
        flash('Invalid request.')
    return redirect(url_for('.index'))

wtxlog/account/templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>{% block title %}{% endblock %} - {{ config['SITE_NAME'] }}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{{ url_for('admin.static', filename='bootstrap/css/bootstrap.css') }}" rel="stylesheet">
<link href="{{ url_for('admin.static', filename='bootstrap/css/bootstrap-responsive.css') }}" rel="stylesheet">
</head>
{# 定义导航菜单 #}
{% set navigation_bar = [
    (url_for('account.index'), 'index', _('Index'), 0),
	(url_for('admin.index'), 'admin', _('Admin'), 2),
	(url_for('account.change_password'), 'change-password', _('Change Password'), 1),
	(url_for('account.change_email_request'), 'change-email', _('Change Email'), 1),
	(url_for('account.logout'), 'logout', _('Logout'), 1),
] -%}
{% set active_page = active_page|default('index') -%}
{% set permission = 0 %}
{% if current_user.is_authenticated() %}{% set permission = 1 %}{% endif %}
{% if current_user.is_administrator() %}{% set permission = 2 %}{% endif %}
<body>
  <div class="container">
  <div class="navbar">
  <div class="navbar-inner">
    <span class="brand"><a href="{{ url_for('main.index') }}">{{ config['SITE_NAME'] }}</a></span>
    <ul class="nav">
      {% for href, id, caption, p in navigation_bar %}
      {% if permission >= p %}<li class="{% if id == active_page %} active{% endif %}"><a href="{{ href|e }}">{{ caption|e }}</a></li>{% endif %}
      {% endfor %}
    </ul>
  </div>
</div>

{% for message in get_flashed_messages() %}
<div class="alert">{{ message }}</div>
{% endfor %}

{% block body %}{% endblock %}
</div>
</body>
</html>

wtxlog/account/templates/change_email.html
{% extends 'base.html' %}

{% set active_page = 'change-email' %}

{% block title %}{{ _('Change Email') }}{% endblock %}

{% block body %}
        <form method="POST" action="">
            <legend>{{ _('Change Email') }}</legend>
            <fieldset>
            {{ form.hidden_tag() if form.hidden_tag }}
            {% for field in form if field.type not in ('CSRFTokenField', 'SubmitField') %}
            <div class="control-group {% if field.errors %}error{% endif %}">
            {{ field.label(class='control-label') }}
                <div class="controls">
                    <div>{{ field }}</div>
                    {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-primary btn-large">{{ _('Change Email') }}</button>
                </div>
            </div>
            </fieldset>
        </form>
{% endblock %}

wtxlog/account/templates/change_password.html
{% extends 'base.html' %}

{% set active_page = 'change-password' %}

{% block title %}{{ _('Change Password') }}{% endblock %}

{% block body %}
        <form method="POST" action="">
            <legend>{{ _('Change Password') }}</legend>
            <fieldset>
            {{ form.hidden_tag() if form.hidden_tag }}
            {% for field in form if field.type not in ('CSRFTokenField', 'SubmitField') %}
            <div class="control-group {% if field.errors %}error{% endif %}">
            {{ field.label(class='control-label') }}
                <div class="controls">
                    <div>{{ field }}</div>
                    {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-primary btn-large">{{ _('Change Password') }}</button>
                </div>
            </div>
            </fieldset>
        </form>
{% endblock %}

wtxlog/account/templates/index.html
{% extends 'base.html' %}

{% block title %}{{ _('Index') }}{% endblock %}

{% block body %}

<div>
    <p><img src="{{ current_user.gravatar() }}" /></p>
    <h1>
        Hello, {{ current_user.username }}!
    </h1>
    {% if not current_user.confirmed %}
    <h3>You have not confirmed your account yet.</h3>
    <p>
        Before you can access this site you need to confirm your account.
        Check your inbox, you should have received an email with a confirmation link.
    </p>
    <p>
        Need another confirmation email?
        <a href="{{ url_for('account.resend_confirmation') }}">Click here</a>
    </p>
    {% endif %}
</div>

{% endblock %}

wtxlog/account/templates/login.html
{% extends 'base.html' %}

{% block title %}{{ _('Login') }}{% endblock %}

{% block body %}
        <form method="POST" action="">
            <legend>{{ _('Login') }}</legend>
            <fieldset>
            {{ form.hidden_tag() if form.hidden_tag }}
            {% for field in form if field.name in ('email', 'password') %}
            <div class="control-group {% if field.errors %}error{% endif %}">
            {{ field.label(class='control-label') }}
                <div class="controls">
                    <div>{{ field }}</div>
                    {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            <div class="control-group">
                <label class="checkbox">{{ form.remember_me }} {{ form.remember_me.label }}</label>
                <div class="controls">
                    <button type="submit" class="btn btn-primary btn-large">{{ _('Login') }}</button>
                </div>
            </div>
            </fieldset>
        </form>
        <p><a href="{{ url_for('account.password_reset_request') }}">{{ _('Forgot your password?') }}</a></p>
        <p><a href="{{ url_for('account.register') }}">{{ _('Need an account? Register free.') }}</a></p>
{% endblock %}

wtxlog/account/templates/register.html
{% extends 'base.html' %}

{% block title %}{{ _('Register') }}{% endblock %}

{% block body %}
        <form method="POST" action="">
            <legend>{{ _('Register') }}</legend>
            <fieldset>
            {{ form.hidden_tag() if form.hidden_tag }}
            {% for field in form if field.type not in ('CSRFTokenField', 'SubmitField') %}
            <div class="control-group {% if field.errors %}error{% endif %}">
            {{ field.label(class='control-label') }}
                <div class="controls">
                    <div>{{ field }}</div>
                    {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-primary btn-large">{{ _('Register') }}</button>
                </div>
            </div>
            </fieldset>
        </form>

        <p><a href="{{ url_for('account.login') }}">{{ _('Already have an account, Login Please.') }}</a></p>
{% endblock %}

wtxlog/account/templates/reset_password.html
{% extends 'base.html' %}

{% block title %}{{ _('Reset Password') }}{% endblock %}

{% block body %}
        <form method="POST" action="">
            <legend>{{ _('Reset Password') }}</legend>
            <fieldset>
            {{ form.hidden_tag() if form.hidden_tag }}
            {% for field in form if field.type not in ('CSRFTokenField', 'SubmitField') %}
            <div class="control-group {% if field.errors %}error{% endif %}">
            {{ field.label(class='control-label') }}
                <div class="controls">
                    <div>{{ field }}</div>
                    {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-primary btn-large">{{ _('Reset Password') }}</button>
                </div>
            </div>
            </fieldset>
        </form>
        <p><a href="{{ url_for('account.login') }}">{{ _('Login') }}</a></p>
{% endblock %}